name: 4dhumans
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pytorch=2.2.1
  - pytorch-cuda=12.1
  - torchvision=0.17.1
  - pip
  - pip:
    - pytorch-lightning
    - smplx==0.1.28
    - pyrender
    - opencv-python
    - yacs
    - scikit-image
    - einops
    - timm
    - dill
    - pandas
    - git+https://github.com/facebookresearch/detectron2
    - git+https://github.com/mattloper/chumpy

#    # For training
#    - rich
#    - hydra-core
#    - hydra-submitit-launcher
#    - hydra-colorlog
#    - pyrootutils
#    - webdataset


